// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: dumbo-ng.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Dumbo-NG
type NGProposal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tx            []byte                 `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"` // hash of previous tx
	Sig           []byte                 `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`   // signature on previous tx
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NGProposal) Reset() {
	*x = NGProposal{}
	mi := &file_dumbo_ng_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NGProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NGProposal) ProtoMessage() {}

func (x *NGProposal) ProtoReflect() protoreflect.Message {
	mi := &file_dumbo_ng_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NGProposal.ProtoReflect.Descriptor instead.
func (*NGProposal) Descriptor() ([]byte, []int) {
	return file_dumbo_ng_proto_rawDescGZIP(), []int{0}
}

func (x *NGProposal) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *NGProposal) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *NGProposal) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type Received struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sigshare      []byte                 `protobuf:"bytes,1,opt,name=sigshare,proto3" json:"sigshare,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Received) Reset() {
	*x = Received{}
	mi := &file_dumbo_ng_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Received) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Received) ProtoMessage() {}

func (x *Received) ProtoReflect() protoreflect.Message {
	mi := &file_dumbo_ng_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Received.ProtoReflect.Descriptor instead.
func (*Received) Descriptor() ([]byte, []int) {
	return file_dumbo_ng_proto_rawDescGZIP(), []int{1}
}

func (x *Received) GetSigshare() []byte {
	if x != nil {
		return x.Sigshare
	}
	return nil
}

// callHelp
type NGCallHelp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Slot          uint32                 `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Sig           []byte                 `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NGCallHelp) Reset() {
	*x = NGCallHelp{}
	mi := &file_dumbo_ng_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NGCallHelp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NGCallHelp) ProtoMessage() {}

func (x *NGCallHelp) ProtoReflect() protoreflect.Message {
	mi := &file_dumbo_ng_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NGCallHelp.ProtoReflect.Descriptor instead.
func (*NGCallHelp) Descriptor() ([]byte, []int) {
	return file_dumbo_ng_proto_rawDescGZIP(), []int{2}
}

func (x *NGCallHelp) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *NGCallHelp) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *NGCallHelp) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type NGHelp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Slot          uint32                 `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Shard         []byte                 `protobuf:"bytes,3,opt,name=shard,proto3" json:"shard,omitempty"`
	Root          []byte                 `protobuf:"bytes,4,opt,name=root,proto3" json:"root,omitempty"`
	Proof1        [][]byte               `protobuf:"bytes,5,rep,name=proof1,proto3" json:"proof1,omitempty"`
	Proof2        []int64                `protobuf:"varint,6,rep,packed,name=proof2,proto3" json:"proof2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NGHelp) Reset() {
	*x = NGHelp{}
	mi := &file_dumbo_ng_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NGHelp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NGHelp) ProtoMessage() {}

func (x *NGHelp) ProtoReflect() protoreflect.Message {
	mi := &file_dumbo_ng_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NGHelp.ProtoReflect.Descriptor instead.
func (*NGHelp) Descriptor() ([]byte, []int) {
	return file_dumbo_ng_proto_rawDescGZIP(), []int{3}
}

func (x *NGHelp) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *NGHelp) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *NGHelp) GetShard() []byte {
	if x != nil {
		return x.Shard
	}
	return nil
}

func (x *NGHelp) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *NGHelp) GetProof1() [][]byte {
	if x != nil {
		return x.Proof1
	}
	return nil
}

func (x *NGHelp) GetProof2() []int64 {
	if x != nil {
		return x.Proof2
	}
	return nil
}

var File_dumbo_ng_proto protoreflect.FileDescriptor

var file_dumbo_ng_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x75, 0x6d, 0x62, 0x6f, 0x2d, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x42, 0x0a, 0x0a, 0x4e, 0x47, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x12, 0x0e,
	0x0a, 0x02, 0x74, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x74, 0x78, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x03, 0x73, 0x69, 0x67, 0x22, 0x26, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x73, 0x69, 0x67, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x73, 0x69, 0x67, 0x73, 0x68, 0x61, 0x72, 0x65, 0x22, 0x44, 0x0a, 0x0a,
	0x4e, 0x47, 0x43, 0x61, 0x6c, 0x6c, 0x48, 0x65, 0x6c, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x6c, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73,
	0x69, 0x67, 0x22, 0x88, 0x01, 0x0a, 0x06, 0x4e, 0x47, 0x48, 0x65, 0x6c, 0x70, 0x12, 0x10, 0x0a,
	0x03, 0x70, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73,
	0x6c, 0x6f, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6f,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x31, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x70,
	0x72, 0x6f, 0x6f, 0x66, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x32, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x32, 0x42, 0x0b, 0x5a,
	0x09, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_dumbo_ng_proto_rawDescOnce sync.Once
	file_dumbo_ng_proto_rawDescData = file_dumbo_ng_proto_rawDesc
)

func file_dumbo_ng_proto_rawDescGZIP() []byte {
	file_dumbo_ng_proto_rawDescOnce.Do(func() {
		file_dumbo_ng_proto_rawDescData = protoimpl.X.CompressGZIP(file_dumbo_ng_proto_rawDescData)
	})
	return file_dumbo_ng_proto_rawDescData
}

var file_dumbo_ng_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dumbo_ng_proto_goTypes = []any{
	(*NGProposal)(nil), // 0: NGProposal
	(*Received)(nil),   // 1: Received
	(*NGCallHelp)(nil), // 2: NGCallHelp
	(*NGHelp)(nil),     // 3: NGHelp
}
var file_dumbo_ng_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dumbo_ng_proto_init() }
func file_dumbo_ng_proto_init() {
	if File_dumbo_ng_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dumbo_ng_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dumbo_ng_proto_goTypes,
		DependencyIndexes: file_dumbo_ng_proto_depIdxs,
		MessageInfos:      file_dumbo_ng_proto_msgTypes,
	}.Build()
	File_dumbo_ng_proto = out.File
	file_dumbo_ng_proto_rawDesc = nil
	file_dumbo_ng_proto_goTypes = nil
	file_dumbo_ng_proto_depIdxs = nil
}
