// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: parbft.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ParBFT
type PREP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           []byte                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Sig           []byte                 `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`           // signature
	Sigshare      []byte                 `protobuf:"bytes,4,opt,name=sigshare,proto3" json:"sigshare,omitempty"` // sigshare
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PREP) Reset() {
	*x = PREP{}
	mi := &file_parbft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PREP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PREP) ProtoMessage() {}

func (x *PREP) ProtoReflect() protoreflect.Message {
	mi := &file_parbft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PREP.ProtoReflect.Descriptor instead.
func (*PREP) Descriptor() ([]byte, []int) {
	return file_parbft_proto_rawDescGZIP(), []int{0}
}

func (x *PREP) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *PREP) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PREP) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *PREP) GetSigshare() []byte {
	if x != nil {
		return x.Sigshare
	}
	return nil
}

type FA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           []byte                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Sig           []byte                 `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"` // signature
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FA) Reset() {
	*x = FA{}
	mi := &file_parbft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FA) ProtoMessage() {}

func (x *FA) ProtoReflect() protoreflect.Message {
	mi := &file_parbft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FA.ProtoReflect.Descriptor instead.
func (*FA) Descriptor() ([]byte, []int) {
	return file_parbft_proto_rawDescGZIP(), []int{1}
}

func (x *FA) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *FA) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *FA) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

var File_parbft_proto protoreflect.FileDescriptor

var file_parbft_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x61, 0x72, 0x62, 0x66, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a,
	0x0a, 0x04, 0x50, 0x52, 0x45, 0x50, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x69, 0x67, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x69, 0x67, 0x73, 0x68, 0x61, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x73, 0x69, 0x67, 0x73, 0x68, 0x61, 0x72, 0x65, 0x22, 0x3c, 0x0a, 0x02, 0x46, 0x41,
	0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x74,
	0x61, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x67, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x69, 0x67, 0x42, 0x0b, 0x5a, 0x09, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_parbft_proto_rawDescOnce sync.Once
	file_parbft_proto_rawDescData = file_parbft_proto_rawDesc
)

func file_parbft_proto_rawDescGZIP() []byte {
	file_parbft_proto_rawDescOnce.Do(func() {
		file_parbft_proto_rawDescData = protoimpl.X.CompressGZIP(file_parbft_proto_rawDescData)
	})
	return file_parbft_proto_rawDescData
}

var file_parbft_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_parbft_proto_goTypes = []any{
	(*PREP)(nil), // 0: PREP
	(*FA)(nil),   // 1: FA
}
var file_parbft_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_parbft_proto_init() }
func file_parbft_proto_init() {
	if File_parbft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_parbft_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_parbft_proto_goTypes,
		DependencyIndexes: file_parbft_proto_depIdxs,
		MessageInfos:      file_parbft_proto_msgTypes,
	}.Build()
	File_parbft_proto = out.File
	file_parbft_proto_rawDesc = nil
	file_parbft_proto_goTypes = nil
	file_parbft_proto_depIdxs = nil
}
