// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: tockcat.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TockCat
type TockCatBest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leader        []byte                 `protobuf:"bytes,1,opt,name=leader,proto3" json:"leader,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Sig1          []byte                 `protobuf:"bytes,3,opt,name=sig1,proto3" json:"sig1,omitempty"`         // signature
	Sig2          []byte                 `protobuf:"bytes,4,opt,name=sig2,proto3" json:"sig2,omitempty"`         // signature
	Sigshare      []byte                 `protobuf:"bytes,5,opt,name=sigshare,proto3" json:"sigshare,omitempty"` // sigshare
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TockCatBest) Reset() {
	*x = TockCatBest{}
	mi := &file_tockcat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TockCatBest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TockCatBest) ProtoMessage() {}

func (x *TockCatBest) ProtoReflect() protoreflect.Message {
	mi := &file_tockcat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TockCatBest.ProtoReflect.Descriptor instead.
func (*TockCatBest) Descriptor() ([]byte, []int) {
	return file_tockcat_proto_rawDescGZIP(), []int{0}
}

func (x *TockCatBest) GetLeader() []byte {
	if x != nil {
		return x.Leader
	}
	return nil
}

func (x *TockCatBest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TockCatBest) GetSig1() []byte {
	if x != nil {
		return x.Sig1
	}
	return nil
}

func (x *TockCatBest) GetSig2() []byte {
	if x != nil {
		return x.Sig2
	}
	return nil
}

func (x *TockCatBest) GetSigshare() []byte {
	if x != nil {
		return x.Sigshare
	}
	return nil
}

var File_tockcat_proto protoreflect.FileDescriptor

var file_tockcat_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x74, 0x6f, 0x63, 0x6b, 0x63, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x7f, 0x0a, 0x0b, 0x54, 0x6f, 0x63, 0x6b, 0x43, 0x61, 0x74, 0x42, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x67, 0x31, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x69, 0x67, 0x31,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x73, 0x69, 0x67, 0x32, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x69, 0x67, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x73, 0x69, 0x67, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x42, 0x0b, 0x5a, 0x09, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tockcat_proto_rawDescOnce sync.Once
	file_tockcat_proto_rawDescData = file_tockcat_proto_rawDesc
)

func file_tockcat_proto_rawDescGZIP() []byte {
	file_tockcat_proto_rawDescOnce.Do(func() {
		file_tockcat_proto_rawDescData = protoimpl.X.CompressGZIP(file_tockcat_proto_rawDescData)
	})
	return file_tockcat_proto_rawDescData
}

var file_tockcat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tockcat_proto_goTypes = []any{
	(*TockCatBest)(nil), // 0: TockCatBest
}
var file_tockcat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tockcat_proto_init() }
func file_tockcat_proto_init() {
	if File_tockcat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tockcat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tockcat_proto_goTypes,
		DependencyIndexes: file_tockcat_proto_depIdxs,
		MessageInfos:      file_tockcat_proto_msgTypes,
	}.Build()
	File_tockcat_proto = out.File
	file_tockcat_proto_rawDesc = nil
	file_tockcat_proto_goTypes = nil
	file_tockcat_proto_depIdxs = nil
}
